Test `Model.search` works.
osohq/oso_odoo pull request #1
Opened 2020-10-14 14:25 UTC by samscott89

2020-10-14 15:25 UTC, samscott89 commented on models/oso.py
> +            # Get all IDs and filter down to just the authorized ones
This is the main change

2020-10-14 15:26 UTC, samscott89 commented on policy/base.polar
> +filter_allow(user, action, [], []);
Not in use, see `_filter_authorized_in_polar` as PoC

2020-10-14 19:17 UTC, plotnick commented on policy/base.polar
>  # Deny everything by default.
I feel pretty strongly that the default base policy should be empty. Could we please move these rules into a test policy?

2020-10-14 20:24 UTC, leina05 requested changes
Awesome! A couple of questions, mainly would like to remove experimental stuff so we keep it separate.

2020-10-14 20:24 UTC, leina05 commented on models/oso.py
> +        self.env["ir.model.access"].clear_caches()
This is just cleanup now that we have `clear_rules()` right?

2020-10-14 20:24 UTC, leina05 commented on models/oso.py
> +        return list(self.groups_id.get_xml_id().values())
This is just to clean this out of the Polar files?

2020-10-14 20:24 UTC, leina05 commented on models/oso.py
> +    _name = "oso.ir.model.access"
Does this actually change behavior or is it just for clarity?

2020-10-14 20:24 UTC, leina05 commented on models/oso.py
> +            _logger.debug(f"class {name} already registered")
This is because we use `clear_rules()` now?

2020-10-14 20:24 UTC, leina05 commented on models/oso.py
> +            arg += [("id", "in", filtered_ids)]
Thinking about how partial eval would fit in with this more... it's not exactly a drop in replacement because the output of partial eval wouldn't be the valid IDs, it would be a more specific set of constraints, right? Like a set of lookup constraints or something?

2020-10-14 20:24 UTC, leina05 commented on models/oso.py
> +        return results
Not very clear on what this would be doing/how it would work. Since it's still experimental, would it be possible to split this into a separate draft PR?

2020-10-14 20:24 UTC, leina05 commented on models/test.py
> +    )
awesome!

2020-10-14 23:56 UTC, samscott89 commented on models/oso.py
> +        self.env["ir.model.access"].clear_caches()
Yep

2020-10-14 23:59 UTC, samscott89 commented on models/oso.py
> +        return list(self.groups_id.get_xml_id().values())
Sort of a perf improvement: it seems wasteful to go back and forth across FFI to (a) get the next group, and (b) to lookup the xml ID one by one.

2020-10-15 00:01 UTC, samscott89 commented on models/oso.py
> +    _name = "oso.ir.model.access"
Behaviour. It allows us to directly look up the oso model in `OsoBase.check_access_rights`. Otherwise I believe you can end up in an infinite loop, depending on how the inheritance structure is set up (I hit this at some point).

2020-10-15 00:02 UTC, samscott89 commented on models/oso.py
> +            _logger.debug(f"class {name} already registered")
I was hitting this a bunch either in tests or when the server was auto reloading. Can't remember which

2020-10-15 00:07 UTC, samscott89 commented on models/oso.py
> +            arg += [("id", "in", filtered_ids)]
Right, it would be a list of [search domains](https://www.odoo.com/documentation/13.0/reference/orm.html#reference-orm-domains). So something like:
```
[("|", ("resource.owner_id", "=", 1), ("resource.public", "is", True))]
```

for

```
resource.owner_id = 1 or
resource.public
```

2020-10-15 00:07 UTC, samscott89 commented on models/oso.py
> +        return results
Yeah, that makes sense

2020-10-15 00:07 UTC, samscott89 commented on policy/base.polar
>  # Deny everything by default.
Sure, good idea.

2020-10-15 01:18 UTC, samscott89 commented on models/oso.py
> +    _name = "oso.ir.model.access"
Hmm, I was starting to second guess myself on this. It didn't sound right. I'm not sure this was correct actually

2020-10-15 02:14 UTC, samscott89 commented on policy/base.polar
>  # Deny everything by default.
This was sadly harder than it should be. Needed to add a way to custom load a policy :/

2020-10-15 02:16 UTC, merged